"""add player/gm calculators and trackers

Revision ID: ab603fc2203e
Revises: a757cb1d62e8
Create Date: 2026-06-03 02:44:15.829605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab603fc2203e'
down_revision: Union[str, Sequence[str], None] = 'a757cb1d62e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('remaining', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timers_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_timers_guild_id'), ['guild_id'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('gm_secret', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_discord_user_id'), ['discord_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_guild_id'), ['guild_id'], unique=False)

    op.create_table('study_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('skill_name', sa.String(length=200), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('real_hours', sa.Float(), nullable=False),
    sa.Column('learning_hours', sa.Float(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_logs_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_logs_discord_user_id'), ['discord_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_logs_skill_name'), ['skill_name'], unique=False)

    op.create_table('wealth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wealth', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wealth_discord_user_id'), ['discord_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wealth', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wealth_discord_user_id'))

    op.drop_table('wealth')
    with op.batch_alter_table('study_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_logs_skill_name'))
        batch_op.drop_index(batch_op.f('ix_study_logs_discord_user_id'))
        batch_op.drop_index(batch_op.f('ix_study_logs_character_id'))

    op.drop_table('study_logs')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_guild_id'))
        batch_op.drop_index(batch_op.f('ix_notes_discord_user_id'))

    op.drop_table('notes')
    with op.batch_alter_table('timers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timers_guild_id'))
        batch_op.drop_index(batch_op.f('ix_timers_channel_id'))

    op.drop_table('timers')
    # ### end Alembic commands ###
