#!/usr/bin/env python
"""Vendor a pinned snapshot of the GCS master library into gurps_bot/data/gcs_library."""

from __future__ import annotations

import argparse
import datetime as _dt
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

# pinned upstream; bump these together to take a new snapshot
REPO_URL = "https://github.com/richardwilkes/gcs_master_library.git"
REPO_SLUG = "richardwilkes/gcs_master_library"
BRANCH = "master"
PINNED_REF = "924a2fd801fccda0e3e32d8bdc430a9403217241"

# extension determines category (rows carry no type field); .skl holds both
# skills and techniques, split downstream by row shape. catalog facts only:
# prose files (.md/.not/.txt/.html) and sheets (.gcs/.gct) are never vendored
CATEGORY_EXTENSIONS: dict[str, str] = {
    "skills": ".skl",
    "traits": ".adq",
    "spells": ".spl",
    "equipment": ".eqp",
}

VENDOR_EXTENSIONS: frozenset[str] = frozenset(CATEGORY_EXTENSIONS.values())

PROJECT_ROOT = Path(__file__).resolve().parent.parent
VENDOR_ROOT = PROJECT_ROOT / "gurps_bot" / "data" / "gcs_library"
VENDOR_LIBRARY = VENDOR_ROOT / "Library"
VENDOR_LICENSE = VENDOR_ROOT / "LICENSE"
VENDOR_PROVENANCE = VENDOR_ROOT / "PROVENANCE.md"


def _utc_now_iso() -> str:
    return _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _run_git(args: list[str], *, cwd: Path | None = None) -> None:
    proc = subprocess.run(
        ["git", *args],
        cwd=str(cwd) if cwd else None,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        cmd = " ".join(["git", *args])
        raise RuntimeError(
            f"git command failed ({proc.returncode}): {cmd}\n"
            f"stdout:\n{proc.stdout}\nstderr:\n{proc.stderr}"
        )


def _clone_pinned(dest: Path) -> None:
    """Full clone (no --depth: the pinned SHA may not be the branch tip), then detach-checkout."""
    # PINNED_REF must be a bare hex SHA, never a ref expression or path
    if not re.fullmatch(r"[0-9a-f]{7,40}", PINNED_REF):
        raise RuntimeError(
            f"PINNED_REF is not a hex SHA (got {PINNED_REF!r}); refusing to check out."
        )
    print(f"Cloning {REPO_URL} (branch {BRANCH}) ...", flush=True)
    _run_git(["clone", "--branch", BRANCH, REPO_URL, str(dest)])
    print(f"Checking out pinned ref {PINNED_REF} ...", flush=True)
    # --detach: take the SHA as-is, never resolve it as a branch or path
    _run_git(["checkout", "--detach", PINNED_REF], cwd=dest)


def _copy_library(src_root: Path) -> int:
    src_library = src_root / "Library"
    if not src_library.is_dir():
        raise RuntimeError(f"upstream Library/ not found at {src_library}")

    # wipe first so upstream removals don't leave stale files
    if VENDOR_LIBRARY.exists():
        shutil.rmtree(VENDOR_LIBRARY)
    VENDOR_LIBRARY.mkdir(parents=True, exist_ok=True)

    copied = 0
    for path in sorted(src_library.rglob("*")):
        # skip symlinks before is_file(), which follows them: an upstream commit
        # could point x.skl at /etc/passwd and copy2 would vendor the target's
        # bytes; pinning doesn't help, the pinned commit can carry the symlink
        if path.is_symlink():
            continue
        if not path.is_file():
            continue
        if path.suffix.lower() not in VENDOR_EXTENSIONS:
            continue
        rel = path.relative_to(src_library)
        dest = VENDOR_LIBRARY / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(path, dest, follow_symlinks=False)
        copied += 1
    return copied


def _copy_license(src_root: Path) -> None:
    # upstream has historically shipped plain LICENSE; accept common variants
    for name in ("LICENSE", "LICENSE.md", "LICENSE.txt", "COPYING"):
        candidate = src_root / name
        if candidate.is_file():
            VENDOR_ROOT.mkdir(parents=True, exist_ok=True)
            shutil.copy2(candidate, VENDOR_LICENSE)
            return
    raise RuntimeError(
        f"no LICENSE file found in upstream checkout at {src_root}"
    )


def _write_provenance(file_count: int) -> None:
    VENDOR_ROOT.mkdir(parents=True, exist_ok=True)
    synced = _utc_now_iso()
    counts = _category_counts()
    count_lines = "\n".join(
        f"- **{cat}** (`{ext}`): {counts[cat]} file(s)"
        for cat, ext in CATEGORY_EXTENSIONS.items()
    )
    content = f"""# Provenance — Vendored GCS Master Library

This directory contains a **pinned, vendored snapshot** of catalog data files
from the GCS master library. It is regenerated by
`tools/sync_gcs_library.py`; do not edit by hand.

## Source

- **Repository:** <https://github.com/richardwilkes/gcs_master_library>
- **Clone URL:** `{REPO_URL}`
- **Branch:** `{BRANCH}`
- **Pinned commit:** `{PINNED_REF}`
- **Synced (UTC):** {synced}
- **Catalog files vendored:** {file_count}

### Per-category file counts

{count_lines}

## Attribution & licensing

- **Data = facts.** The vendored `.skl` / `.adq` / `.spl` / `.eqp` files are GURPS
  Character Sheet (GCS) JSON. The *facts* they encode — names, governing
  attributes, difficulty codes, point costs, page references, and mechanical
  relations (defaults, prerequisites, casting costs, damage codes, etc.) — are
  used under the **Steve Jackson Games Online Policy**. GURPS is a trademark of
  Steve Jackson Games, used under that policy; this project is not affiliated
  with or endorsed by Steve Jackson Games.
- **Code / compilation © Richard Wilkes**, licensed under the **Mozilla Public
  License, Version 2.0 (MPL-2.0)**. The upstream license text is vendored
  verbatim alongside this file as `LICENSE`.

## Updating

To ingest upstream changes, bump `PINNED_REF` (and `BRANCH` if it moves) in
`tools/sync_gcs_library.py`, then re-run:

```sh
uv run python tools/sync_gcs_library.py
```

Verify the result with:

```sh
uv run python tools/sync_gcs_library.py --check
```
"""
    VENDOR_PROVENANCE.write_text(content, encoding="utf-8")


def _category_counts() -> dict[str, int]:
    counts = {cat: 0 for cat in CATEGORY_EXTENSIONS}
    if not VENDOR_LIBRARY.is_dir():
        return counts
    for cat, ext in CATEGORY_EXTENSIONS.items():
        counts[cat] = sum(
            1
            for p in VENDOR_LIBRARY.rglob(f"*{ext}")
            if p.is_file()
        )
    return counts


def _book_folders() -> list[str]:
    if not VENDOR_LIBRARY.is_dir():
        return []
    return sorted(p.name for p in VENDOR_LIBRARY.iterdir() if p.is_dir())


def cmd_sync() -> int:
    with tempfile.TemporaryDirectory(prefix="gcs_master_library_") as tmp:
        clone_dir = Path(tmp) / "repo"
        _clone_pinned(clone_dir)

        print("Copying catalog files ...", flush=True)
        file_count = _copy_library(clone_dir)
        print(f"  copied {file_count} catalog file(s)", flush=True)

        print("Copying LICENSE ...", flush=True)
        _copy_license(clone_dir)

    print("Writing PROVENANCE.md ...", flush=True)
    _write_provenance(file_count)

    print("\nDone. Vendored snapshot summary:", flush=True)
    return _print_check()


def cmd_check() -> int:
    return _print_check()


def _print_check() -> int:
    print(f"Vendor root:    {VENDOR_ROOT}")
    print(f"Pinned ref:     {PINNED_REF}")

    if not VENDOR_LIBRARY.is_dir():
        print("Status:         NOT VENDORED (Library/ missing)")
        print("Run:            uv run python tools/sync_gcs_library.py")
        return 1

    counts = _category_counts()
    books = _book_folders()
    total = sum(counts.values())

    print(f"LICENSE:        {'present' if VENDOR_LICENSE.is_file() else 'MISSING'}")
    print(
        f"PROVENANCE.md:  "
        f"{'present' if VENDOR_PROVENANCE.is_file() else 'MISSING'}"
    )
    print(f"Book folders:   {len(books)}")
    print("Per-category file counts:")
    for cat, ext in CATEGORY_EXTENSIONS.items():
        print(f"  {cat:<12} ({ext}): {counts[cat]}")
    print(f"Total catalog files: {total}")

    # empty skills category means the vendor ran but produced nothing useful
    return 0 if counts.get("skills", 0) > 0 else 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="sync_gcs_library",
        description=(
            "Vendor the pinned GCS master library snapshot into "
            "gurps_bot/data/gcs_library/."
        ),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Dry run: verify vendored dir + print per-category counts (no network).",
    )
    args = parser.parse_args(argv)

    try:
        if args.check:
            return cmd_check()
        return cmd_sync()
    except Exception as exc:  # surface a clean failure for the CLI/test caller
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
